# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/179Do8gGDTNKyEiAXi6ECydT3V4QKknz7
"""

import cv2
face_cascade = cv2.CascadeClassifier('face_detector.xml') #Loading neural network
img=cv2.imread('image.jpeg')
faces = face_cascade.detectMultiScale(img,1.1,4) #Detecting the faces
for (x, y, w, h) in faces:
 cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)
 cv2.imwrite("face_detected.png", img) #Drawing a rectangular box around the face
 print('photo successfully exported')

"""# New Section"""